

X. 16-a.ning 2-yarmidan Xorazmning poytaxtiga aylangach, har tomonlama rivojlandi. Me?moriy qiyofasi ham o?zgara bordi. Shahardan o?zaro ko?ndalang kesishgan 2 ta katta ko?cha va 4 darvoza (Otadarvoza, Polvondarvoza, Bog?chadarvoza, Toshdarvoza) orqali Dishan qal?a (rabod) ga chiqiladi. Ichan qal?a devorining uz. 2200 m, bal. 6— 8 m, tag zaminining qalinligi 5—6 m. Qal?a to?g?ri to?rtburchak shaklida qurilgan bo?lib, uz. 650 m, eni 400 m, jami 26 ga maydonga ega.

X.ning rabod qismi Dishan qal?a 1842 y. Olloqulixon davrida (1825— 42) baland devor bilan o?rab olingan. O?sha davrda Ichan qal?ada 33 mahalla (machitqavm) va Dishan qal?ada 34 mahalla bo?lgan. Mahallalar nomi shu yerda yashayotgan aholining kasbkori (Chitkarlik, Elakchilik, Kulollar, Misgarlik, G?assollar) yoki shaxs lavozimi (Otamurod qushbegi, Yoqub mehtar, Yusuf yasovulboshi) bilan atalgan. Shaharda 109 kattakichik ko?cha, 79 masjid va 120 qorixona bo?lgan. X.da 19-a. o?rtalarida 20 ming kishi yashagan. Shahar, asosan, 19-a.ning 2-yarmidan kengaya bordi.

1874 y.da shahar ma?muriy jihatdan Qumyosqa, Kaptarxona, O?r, Ko?hnabozor, Kaltaminor, Amin chorsu, Mevaston, Qoraa?lam va Yangi qal?a mavzelariga bo?lingan. X. xonning "mulki xolisasi" hisoblanib shaxsan uning o?zi tomonidan boshqarilgan. 19-a. oxiri — 20-a. boshlarida X.da 64 Madrasa, 79 masjid bo?lgan. 1924 y. shaharda olingan aholi ro?yxatida 4029 xonadonda 18145 kishi qayd qilingan.

X.ning ilk tarhi 1740 y.da chizilgan. Shahar tarhi uzunasiga 1 ming m, eniga 400 m bo?lib, 40 ga maydonni egallagan. Uning butun tevarak atrofi suvli xandaq bilan o?rab olingan. Shaharga sharq tomondan maxsus ko?prik orqali kirish mumkin bo?lgan. Ko?prik kechalari ko?tarib qo?yilgan. Ko?prik yonidagi darvozadan boshlangan katta ko?cha to?ppato?g?ri Ark darvozasiga borib taqalgan. Ark shaharning g?arbiy qismida joylashgan. Shaharning asosiy ko?chasi uni 2 qism (shim. va jan.) ga ajratgan. Arkda xon saroyi, haramxona, aslahaxona bo?lib, ular maxsus qal?a devori bilan o?ralgan. Lekin, o?sha davrdagi ba?zi inshootlar chizmaga kirmay qolgan. Shaharning yana bir tarhi Rossiyadan maxfiy topshiriq bilan kelgan topograf G.N.Zelenin tomonidan 1839 y.da chizilgan. Zeleninning ma?lumotlariga ko?ra, shaharda o?sha davrda 17 ta masjid, 22 ta mahalla va 260 savdo rastasi bo?lgan. Shaharning juda aniq va mukammal bo?lgan so?nggi tarhi 1873 y.gi rus istilosidan so?ng rus topograflari tomonidan tuzilgan va o?sha yiliyoq "1873 yilgi Xiva yurishlari" maqolasiga ilova tarzida bosilgan.

Me?moriy ansamblining yaxlitligi jihatidan shahar O?rta Osiyoda yagona hisoblanadi. 1967 y.da O?rta Osiyoda ilk bor X.ning Ichan qal?a (shahriston) qismi tarixiyme?moriy yodgorliklar qo?riqxonasi deb e?lon qilindi. X.ning jahon madaniyati taraqqiyotida tutgan o?rni YUNESKO Bosh konferensiyasining (1995 y. okt.—noyab.) 28sessiyasida alohida qayd qilindi. O?zbekiston Respublikasi Vazirlar Mahkamasining 1996 y. 3 yanv.dagi qarori bilan X.ning 2500 yilligi 1997 y.da jahon miqyosida keng nishonlandi.

Shaharda "XivaKarpet" qo?shma korxonasi, sopol buyumlar, paxta tozalash, g?isht zavodlari, tikuvchilik, "Xiva gidami" aksiyadorlik jamiyati va b. gilam to?qish korxonalari, non kti, dehqon bozori, madaniy, savdo va maishiy xizmat ko?rsatish shoxobchalari faoliyat ko?rsatadi. Urganch universitetining agromenejment fti, O?zbekiston FAning Xorazm Ma?mun akademiyasi bo?limi, Qoraqum i.t. stansiyasi, ped., tibbiyot, turizm kasb-hunar kollejlari, kasbhunar litseyi, gimnaziya, 15 umumiy ta?lim maktabi, mehribonlik uyi, 2 maxsus internat, viloyat qo?g?irchoq teatri, san?at maktabi, 2 kutubxona va uning tarmoqdari, madaniyat va istirohat bog?i mavjud. AlXorazmiy, Feruz yodgorliklari, birinchi o?zbek kinooperatori Xudoybergan Devonov muzeyi, markaziy stadion, sport majmuasi, tennis korti, sport zallari va b. sport inshootlari bor.

Tuman markaziy kasalxonasi, poliklinika, tug?ruqxona, bolalar kasalxonasi, tish davolash markazi, markaziy dorixona, xususiy dorixonalar va b. tibbiy muassasalar mavjud.

Tarixiy-me?moriy obidalardan Sayd Aloviddin maqbarasi, Pahlavon Maxmud majmuasi, Juma masjid, Ko?hna Ark, Oqshayx bobo ko?shki, Toshhovli, Nurullaboy saroyi, Muhammad Aminxon madrasasi, Muhammad Rahimxon madrasasi, Islomxo?ja madrasasi va minorasi, Olloqulixon madrasasi, Qutlug?murod inoq madrasasi, Olloqulixon karvonsaroyi va timi, Anushaxon xammomi, Oq masjid, Polvon darvoza, Ota darvoza, Bog?cha darvoza, Tosh darvoza, Hazorasp darvoza, Kush darvoza va b. saqlanib qolgan.

Shaharda "Xiva—Sharq gavhari" jurnali (2001 y.dan), "Xiva tongi" tuman gaz. nashr etiladi. Shahar jahon turizmi markazlaridan birga aylangan. X.ga har yili 200 mingdan ziyod sayyoh, shu jumladan, 7 mingga yaqin xorijlik sayyoh va mehmonlar tashrif buyuradi. Shaharda "O?zbekturizm" milliy kompaniyasiga qarashli va bir necha xususiy mehmonxonalar ishlab turibdi.

X.dan Urganch sh.ga trolleybus katnovi yo?lga qo?yilgan (1997). X.—Toshkent, X.—Buxoro, X.—Navoiy—Samarkand—Toshkent yo?nalishida, shuningdek, Urganch, Qo?shko?pir, Yangiariq, Bog?ot, Hazorasp va viloyatdagi boshqa shahar va yirik aholi punktlariga avtobuslar va marshrutli taksilar qatnaydi.